apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  labels:
    app: modulith-init
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: postgres-init
        image: postgres:16-alpine
        command: ["sh", "-c", "until pg_isready -h postgres -p 5432; do echo 'Waiting for PostgreSQL...'; sleep 2; done; echo 'PostgreSQL is ready!'"]
        resources:
          limits:
            cpu: "0.1"
            memory: "64Mi"
          requests:
            cpu: "0.05"
            memory: "32Mi"
      restartPolicy: OnFailure